### ISSUE TITLE
bug in sidekiq service

### ISSUE THREAD

**Issue by narender2031** [hellostealth/stealth#124]
there is bug in messageHandle job if message is empty then it gives error. if you take it as a bug then i will love to fix the issue

**Comment by mgomes** [comment]
Hi @narender2031, could you provide some more info as to what message is getting passed in and what the error is? A pull request would also be welcomed.

**Comment by narender2031** [comment]
issue in the stealth-facebook/lib/stealth/services/facebook/message_handler.rb
in a process method line no 40 
if the message is empty it gives the  following error
undefined method `first' for nil:NilClass

**Comment by mgomes** [comment]
I have to go through the FB docs a bit. Not quite sure why a message would come in without that field set. A lot of the code depends on that though, so it's not as simple as checking for `nil`.

**Comment by mgomes** [comment]
I am going to close this one. I think what is happening is that a different type of web hook is coming in rather than one supported by the facebook driver. If the problem persists for a `messages` or `postbacks` web hook, feel free to re-open this on the https://github.com/hellostealth/stealth-facebook repo.
