### ISSUE TITLE
How to handle different locales?

### ISSUE THREAD

**Issue by josephktcheung** [hellostealth/stealth#187]
Hi does Stealth support multiple locales?

**Comment by mgomes** [comment]
Hello @josephktcheung what specifically are you looking for in terms of locales?

**Comment by josephktcheung** [comment]
For example, MS bot framework can create multi-lingual bot https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-localization?view=azure-bot-service-3.0.
Simple use case: send messages based on user's locale available in FB user profile API https://developers.facebook.com/docs/messenger-platform/identity/user-profile#fields

**Comment by mgomes** [comment]
Ah ok. Internationalization is definitely on our roadmap but it isn't support out of the box right now. But you could definitely do something similar to what the MS Bot framework currently supports. 

Long term though I18n would look like variants. So replies would automatically be selected based on locale:

`say_hello.yml`
`say_hello.pt-br.yml`
`say_hello.es.yml`

And so on. With the upcoming Stealth 2.0, you are able to specify custom reply filenames and paths. So that would help move the locale logic to your controllers instead of your replies.

**Comment by josephktcheung** [comment]
@mgomes thanks and look forward to trying Stealth 2.0 out :)
