### ISSUE TITLE
Running stealth generate flow <NAME> generates wrong controller name 

### ISSUE THREAD

**Issue by debasish117** [hellostealth/stealth#67]
**Describe the bug**
Running `stealth generate flow <NAME>` generates wrong controller name . The name is not according to naming conventions. The name is generated in pluralised form but not in camel case. 

**To Reproduce**
1. run `stealth generate flow camel_cased` 

**Expected behavior**
`CamelCasedController < BotController`

**Current behaviour**
`camelCasedController < BotController`

**Additional Information**
I am working on the issue, just wanted to inform about the bug which i came across while using the gem. Just awaiting for your response and I will be raising a PR once i get a response from your side .

**Comment by matthewblack** [comment]
Hey @debasish117 - Confirmed as a bug. 

Do you want to send over a PR? Thanks :)

**Comment by debasish117** [comment]
@matthewblack i have already a fix in my fork. I will create a PR soon please do review and revert back.

**Comment by matthewblack** [comment]
👍

On May 25, 2018 at 8:10 AM, debasish_dhal117 <notifications@github.com>
wrote:


@matthewblack <https://github.com/matthewblack> i have already a fix in my
fork. I will create a PR soon please do review and revert back.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/hellostealth/stealth/issues/67#issuecomment-392033619>,
or mute the thread
