### ISSUE TITLE
Example of CatchAll use

### ISSUE THREAD

**Issue by luizcarvalho** [hellostealth/stealth#88]
Hello my friends, 

1) Anybody have a simple and practical example of catch all use with multiples levels?

2) Exist the possibility to get a rescued error in levels actions to customize messages?

Thanks :D

**Comment by mgomes** [comment]
Hi @luizcarvalho!

Here's what a typical `catch_alls_controller.rb` looks like for us:

```ruby
class CatchAllsController < BotController

  def level1
    send_replies

    if previous_session_specifies_fails_to?
      step_to flow: previous_session.flow_string, state: previous_state.to_s
    else
      step_to session: previous_session - 2.states
    end
  end

  def level2
    send_replies

    if previous_session_specifies_fails_to?
      step_to flow: previous_session.flow_string, state: previous_state.to_s
    else
      step_to session: previous_session - 2.states
    end
  end

  def level3
    send_replies
  end

private

   def previous_session_specifies_fails_to?
     previous_state.present?
   end

   def previous_state
     previous_session.flow.current_state.fails_to
   end

end
```

As you can see it is pretty generic. Once we get to the last level (`level3` here), we don't redirect the user back anymore. Here we would typically hand off to a human or ask the user to contact support because something has really gone wrong.

With respect to getting access to error messages, I am not sure this is something we will support. If you want to catch errors in order to return a message to the user, you should do that in your controller action. The `CatchAll` is designed for unexpected failures. You can think of the `CatchAll` like a 500 error page and not a form error. Does that make sense?

**Comment by luizcarvalho** [comment]
@mgomes Nice approach in the catch all levels, I understand now what is the objective. Made sense to me. Very thanks for the explanation.
